/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThesisRouteImport } from './routes/thesis'
import { Route as TeamRouteImport } from './routes/team'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HandshakeRouteImport } from './routes/handshake'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing/index'
import { Route as WritingSlugRouteImport } from './routes/writing/$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout/cancel'

const ThesisRoute = ThesisRouteImport.update({
  id: '/thesis',
  path: '/thesis',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HandshakeRoute = HandshakeRouteImport.update({
  id: '/handshake',
  path: '/handshake',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/atlas': typeof AtlasRoute
  '/handshake': typeof HandshakeRoute
  '/pricing': typeof PricingRoute
  '/team': typeof TeamRoute
  '/thesis': typeof ThesisRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/atlas': typeof AtlasRoute
  '/handshake': typeof HandshakeRoute
  '/pricing': typeof PricingRoute
  '/team': typeof TeamRoute
  '/thesis': typeof ThesisRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing': typeof WritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/atlas': typeof AtlasRoute
  '/handshake': typeof HandshakeRoute
  '/pricing': typeof PricingRoute
  '/team': typeof TeamRoute
  '/thesis': typeof ThesisRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/atlas'
    | '/handshake'
    | '/pricing'
    | '/team'
    | '/thesis'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/writing/$slug'
    | '/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/atlas'
    | '/handshake'
    | '/pricing'
    | '/team'
    | '/thesis'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/writing/$slug'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/atlas'
    | '/handshake'
    | '/pricing'
    | '/team'
    | '/thesis'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/writing/$slug'
    | '/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AtlasRoute: typeof AtlasRoute
  HandshakeRoute: typeof HandshakeRoute
  PricingRoute: typeof PricingRoute
  TeamRoute: typeof TeamRoute
  ThesisRoute: typeof ThesisRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  WritingSlugRoute: typeof WritingSlugRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thesis': {
      id: '/thesis'
      path: '/thesis'
      fullPath: '/thesis'
      preLoaderRoute: typeof ThesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handshake': {
      id: '/handshake'
      path: '/handshake'
      fullPath: '/handshake'
      preLoaderRoute: typeof HandshakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AtlasRoute: AtlasRoute,
  HandshakeRoute: HandshakeRoute,
  PricingRoute: PricingRoute,
  TeamRoute: TeamRoute,
  ThesisRoute: ThesisRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  WritingSlugRoute: WritingSlugRoute,
  WritingIndexRoute: WritingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
